# 项目名称
name: Build&Push

on:
  workflow_dispatch:
  # 代码推送到master分支触发
  #push:
   # branches: [ "master" ]

jobs:
  build:
    # 运行环境
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: zip -r data.zip .
    - run: ls -l
 # 上传部署
    - name: scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.YUXUAN_MAIN_SERVER_IP }}
        user: ${{ secrets.YUXUAN_MAIN_SERVER_USER }}
        pass: ${{ secrets.YUXUAN_MAIN_SERVER_PASS }}
        scp: |
          ./data.zip => /mnt/project/php/api
        last_ssh: |
          echo $LASTSSH 
          cd /mnt/project/php/api
          unzip -o data.zip
          rm data.zip
  
